name: Deploy Terraform and Prototype App

on:
  push:
    branches:
      - module02   # later change to main

env:
  AWS_REGION: eu-west-1                     # set your region
  S3_BUCKET: amir-photostory-s3-repo        # bucket that serves the site
  CLOUDFRONT_DISTRIBUTION_ID: ES6ZB8XJ2PHU4  # your distribution ID

jobs:
  terraform:
    name: Terraform Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform

  build-and-deploy:
    name: Build Prototype App and Deploy
    runs-on: ubuntu-latest
    needs: terraform

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Dependencies
        run: |
          npm ci
        # set working-directory if app is in a folder
        working-directory: .  

      - name: Build Prototype App
        run: |
          npm run build
        working-directory: .  

      - name: Sync dist/ to S3
        run: aws s3 sync dist/ s3://${{ env.S3_BUCKET }} --delete
        working-directory: .  

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ env.CLOUDFRONT_DISTRIBUTION_ID }} \
     	    --paths "/*"

